name: clubedaregua_shared
description: Código compartilhado entre App Cliente e App Gestão do Clube da Régua.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
